### ISSUE TITLE
(0.5) Marathon auth token

### ISSUE THREAD

**Issue by tuxity** [e20co/drone-marathon#5]
It could be nice to add the possibility to set the marathon auth token in the requests headers when your drone is outside the cluster.

`Authorization: token=${MARATHON_TOKEN}`

I would like to use this plugin to trigger a restart of a task but my drone server is running outside of the cluster and I get a 403 Forbidden error

**Comment by dellintosh** [comment]
That sounds like a pretty valid request... (We are running our server and agents inside the cluster thanks to [our Universe fork](https://github.com/e20co/universe)).  I might have some time this weekend to tinker around with this module some more (there are a couple other items I want to improve as well).

**Comment by dellintosh** [comment]
ok, so it looks like secrets have changed recently per [here](http://discourse.drone.io/t/secret-change-back-to-interpolation/189).  As such, I'm thinking of handling this request as something like:

```yaml
pipeline:
  marathon:
    ...
    auth_token: ${MARATHON_AUTH_TOKEN}  # or other value, as secret
```

I'm not sure that supporting other headers will be needed since all requests are handled by the plugin.

**Comment by tuxity** [comment]
I'm not really agree by putting directly a token in the yaml file because this plugin is for marathon. We should not change the logic because we use a marathon behind DC/OS which secure marathon api with a token

On another project I saw a field where you can setup headers, but only `Authorization` and `Content-type` headers are authorized. 

We can do something like that:

```
pipeline:
  marathon:
    ...
    headers:
      - Authorization="token=<authentication-token>"
      - Custom-Header=custom-value
```
On this example, only Authorization will be added to the request.
